apiVersion: v1
kind: Service
metadata:
  name: fernanda-api-service
  namespace: api-fernanda
spec:
  selector:
    app: fernanda-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30001
  type: NodePort 